import { StyleSheet } from 'react-native';

export const gStyle = StyleSheet.create({
    mainLogin: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 55,
        borderWidth:2,
        marginTop:38,
        paddingHorizontal:10,
        borderColor:'#FF0000',
        borderRadius:23,
        paddingVertical:2,
    },
    title: {
        fontSize: 20,
        color: '#333',
    },
    buttonLogin: {
        //flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 55,
        borderWidth:2,
        marginTop:50,
        paddingHorizontal:10,
        backgroundColor:'#FF0000',
        borderColor:'#FF0000',
        borderRadius:23,
        paddingVertical:8,
    },
    buttonRegister: {
        //flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 55,
        borderWidth:2,
        marginTop:50,
        paddingHorizontal:10,
        backgroundColor:'#00716F',
        borderColor:'#00716F',
        borderRadius:23,
        paddingVertical:8,
    },
    buttonText: {
        alignItems: 'center',
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: 'bold',
    },
    mainRegister: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 55,
        borderWidth:2,
        marginTop:28,
        paddingHorizontal:10,
        borderColor:'#00716F',
        borderRadius:23,
        paddingVertical:2,
    },
})